// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CBMiOS
{
	public partial class LogVC : UIViewController
	{
		public LogVC (IntPtr handle) : base (handle)
		{
		}
	}
}
